$(function(){
	$(window).scroll(function(){
		if($(this).scrollTop()>400){
			$('.top_bt').fadeIn('fast')
		}else{
			$('.top_bt').fadeOut('fast')
		}
	})
	$('.top_bt').click(function(){
		$('html,body').animate({scrollTop:0},200)
	})
});

$(function(){
	$(window).scroll(function(){
		if($(this).scrollTop()>400){
			$('.bottom_bt').fadeIn('fast')
		}else{
			$('.bottom_bt').fadeOut('fast')
		}
	})
	$('.bottom_bt').click(function(){
		$('html,body').animate({scrollTop:$(document).height()},200)
	})
})